services:
  - type: web
    name: mindmitra-backend
    env: node
    plan: free

    buildCommand: npm install
    startCommand: node src/server.js

    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGO_URI
        sync: false

      - key: ACCESS_TOKEN_SECRET
        sync: false

      - key: ACCESS_TOKEN_EXPIRY
        value: 15m

      - key: REFRESH_TOKEN_SECRET
        sync: false

      - key: REFRESH_TOKEN_EXPIRY
        value: 7d

      - key: CLIENT_URL
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: RESEND_API_KEY
        sync: false

      - key: EMAIL_FROM
        value: "MindMitra <onboarding@resend.dev>"

      - key: METERED_DOMAIN
        sync: false

      - key: METERED_API_KEY
        sync: false

      - key: ICE_SERVERS
        sync: false